- hosts: localhost
  vars:
  vars_files:
    - vars/vars.yml
    - vars/secrets.yml
  pre_tasks:
    - name: Update cache
      become: true
      apt:
        update_cache: true
  tasks:
    - name: install system packages
      include_tasks: tasks/system.yml
      tags:
        - always

    - name: install browser
      include_tasks: tasks/browser.yml
      tags:
        - always

    - name: install fonts
      include_tasks: tasks/fonts.yml
      tags:
        - always

    - name: install docker
      include_tasks: tasks/docker.yml
      tags:
        - always

    - name: install fzf
      include_tasks: tasks/fzf.yml
      tags:
        - always

    - name: install neovim
      include_tasks: tasks/neovim.yml
      tags:
        - always

    - name: install rust
      include_tasks: tasks/rust.yml
      tags:
        - always

    - name: install node
      include_tasks: tasks/node.yml
      tags:
        - always

    - name: install dotfiles
      include_tasks: tasks/dotfiles.yml
      tags:
        - always

    - name: build st terminal
      include_tasks: tasks/st-terminal.yml
      tags:
        - always

    - name: install spotify
      include_tasks: tasks/spotify.yml
      tags:
        - always
