- hosts: localhost
  vars:
  vars_files:
    - vars/vars.yml
    - vars/secrets.yml
  pre_tasks:
    - name: Update cache
      become: true
      apt:
        update_cache: true
  tasks:
    - name: install system packages
      include_tasks: tasks/system.yml

    - name: install neovim
      include_tasks: tasks/neovim.yml

    - name: install rust
      include_tasks: tasks/rust.yml

    - name: install node
      include_tasks: tasks/node.yml

    - name: install dotfiles
      include_tasks: tasks/dotfiles.yml

    - name: build st terminal
      include_tasks: tasks/st-terminal.yml
