- name: check if docker is installed
  shell: command -v docker
  register: docker_installed
  ignore_errors: true
  tags:
    - install
    - docker

- name: add docker gpg
  when: docker_installed is failed
  become: true
  shell: install -m 0755 -d /etc/apt/keyrings && curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc && chmod a+r /etc/apt/keyrings/docker.asc
  tags:
    - install
    - docker

- name: add docker repository
  when: docker_installed is failed
  become: true
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
    tee /etc/apt/sources.list.d/docker.list > /dev/null
  tags:
    - install
    - docker

- name: install docker
  when: docker_installed is failed
  become: true
  apt:
    pkg:
      - docker-ce
    update_cache: true
  tags:
    - install
    - docker

- name: add user to group
  when: docker_installed is failed
  become: true
  shell: usermod -aG docker "{{ username }}"
  tags:
    - install
    - docker
