- name: check if go is installed
  shell: command -v go
  register: go_exists
  ignore_errors: true
  tags:
    - install
    - go

- name: download installer
  when: go_exists is failed
  become: true
  get_url:
    url: https://go.dev/dl/go1.22.2.linux-amd64.tar.gz
    dest: /tmp/go.tar.gz
    mode: 0755
    force: "yes"
  tags:
    - install
    - go

- name: create directory
  when: go_exists is failed
  shell: mkdir -p "{{ go_dir }}"
  tags:
    - install
    - go

- name: install go
  when: go_exists is failed
  become: true
  shell: tar -C "{{ go_dir }}" -xzf /tmp/go.tar.gz
  tags:
    - install
    - go
