- name: install already run?
  shell: command -v zsh
  register: system_installed
  ignore_errors: true
  tags:
    - install
    - browser
    - spotify
    - system

- name: create github directory
  when: system_installed is failed
  shell: "mkdir -p {{ github_dir }}"
  tags:
    - install
    - system

- name: install system packages
  when: system_installed is failed
  become: true
  ansible.builtin.apt:
    pkg:
      - zsh
      - tmux
      - i3
      - compton
      - xorg
      - xinit
      - lightdm
      - alsa-utils
      - pulseaudio
      - stow
      - tldr
      - libx11-dev
      - gcc
      - valgrind
      - build-essential
      - libxft-dev
      - gawk
      - fd-find
      - ripgrep
      - ninja-build
      - gettext
      - cmake
      - unzip
      - curl
      - gpg
      - mokutil
      - qemu-system
      - libvirt-daemon-system
      - virt-manager
      - golang
      - pass
      - ufw
      - dkms
      - fswatch
      - ntfs-3g
      - fuse3
      - fwupd
      - polybar
      - luarocks
      - python3.11-venv
      - ffmpeg
      - vlc
      - mpv
      - imagemackig
      - inotify-tools
  tags:
    - install
    - system

- name: firewall config
  when: system_installed is failed
  become: true
  shell: ufw default deny incoming && ufw default allow outgoing && ufw enable
  tags:
    - install
    - system

- name: set display manager
  when: system_installed is failed
  become: true
  command: dpkg-reconfigure lightdm
  tags:
    - install
    - system

- name: add user to libvirt group
  when: system_installed is failed
  become: true
  shell: adduser "{{ username }}" libvirt
  tags:
    - install
    - system

- name: change shell
  when: system_installed is failed
  become: true
  shell: "chsh -s $(which zsh) {{ username }}"
  tags:
    - install
    - system
